# Generated by Django 4.2.1 on 2023-06-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(max_length=50)),
                ('full_code', models.CharField(max_length=50)),
                ('abbrev_desc', models.CharField(max_length=255)),
                ('full_desc', models.TextField()),
                ('status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='codes.category')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('category', 'full_code')},
            },
        ),
    ]
