# Generated by Django 4.2.1 on 2023-06-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=10),
        ),
    ]
